Repository renanbreier/DatingApp-FlutterProject, pull requests merged in 2025-04, with the labels that each got.

#4 tela_phoneNumber
  lib/screens/phone_number_screen.dart
  lib/widgets/login_form_widget.dart
  pubspec.lock
  pubspec.yaml
Labels: Implementação

#8 verification_screen
  lib/screens/phone_number_screen.dart
  lib/screens/verification_screen.dart
Labels: Implementação

#10 função para validar número
  lib/screens/phone_number_screen.dart
Labels: Melhoria

#12 função para validar código de verificação
  lib/screens/profile_screen.dart
  lib/screens/verification_screen.dart
Labels: Melhoria

#13 Atualização do README
  README.md
Labels: Documentação

#15 correção da função
  lib/assets/icons/apple.png
  lib/assets/icons/facebook.png
  lib/assets/icons/google.png
  lib/screens/login_screen.dart
  lib/screens/phone_number_screen.dart
  lib/widgets/login_form_widget.dart
  pubspec.yaml
Labels: Correção de bug

#16 Atualizando o README
  README.md
Labels: Documentação

#17 telaperfil
  lib/assets/profile.jpg
  lib/screens/profile_screen.dart
  lib/screens/verification_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: Implementação

#22 tradução pt-br
  lib/screens/login_screen.dart
  lib/screens/phone_number_screen.dart
  lib/screens/verification_screen.dart
Labels: Melhoria

#23 função para só aceitar número
  lib/screens/phone_number_screen.dart
Labels: Correção de bug

#24 Correção da tela de Perfil
  lib/main.dart
  lib/screens/profile_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: Correção de bug

#25 Criação da tela principal
  lib/screens/main_screen.dart
  lib/screens/profile_screen.dart
Labels: Implementação

#26 Documentação
  lib/main.dart
  lib/screens/login_screen.dart
  lib/screens/phone_number_screen.dart
  lib/screens/profile_screen.dart
  lib/screens/verification_screen.dart
Labels: Documentação
